### ISSUE TITLE
Custom Insight configuration documentation clarification 

### ISSUE THREAD

**Issue by kostuch-sumologic** [SumoLogic/sumologic-documentation#1886] opened 2023-03-16 14:42 UTC
**Describe the bug:**
The Configure a Custom Insight help page does not adequately explain or address the inclusion of related signals.  
https://help.sumologic.com/docs/cse/records-signals-entities-insights/configure-custom-insight/

**Expected behavior:**
Based on the current help doc, customers expect only the signals directly involved with the custom insight to be displayed and not related signals.

However, according to Engineering: When a Custom Insight triggers, it will include the signals that it fired on, but also any other Signals that are in the trailing look back window for context (14 days by default). Think of a Custom Insight as a short-circuit to the default severity-based insight system. This is expected behavior per engineering.  

Please revise the documentation to address the inclusion of related signals in the CSE results.  

**Screenshots**
![image (2)](https://user-images.githubusercontent.com/106690344/225649589-918c2a54-91a4-4530-98a8-dbc3aa1ab155.png)
In this screen capture from a client environment, the top signal is a related signal (not expected to be displayed) and the bottom signal the custom created signal.  

**Additional info:**
Also, searching for Custom Insight using Algolia does not show this result page -- https://help.sumologic.com/docs/cse/records-signals-entities-insights/configure-custom-insight/

**Comment by jpipkin1** [comment] 2023-04-25 20:31
@kostuch-sumologic, with [PR 1886](https://github.com/SumoLogic/sumologic-documentation/pull/2198) I added the following sentence to the article:

> The generated Insights will include not only the Signals that it fired on, but also any related Signals.

**Comment by jpipkin1** [comment] 2023-04-27 17:30
The issue is closed by [PR 2198](https://github.com/SumoLogic/sumologic-documentation/pull/2198).

**Closed by jpipkin1** 2023-04-27 17:30 UTC
Labels: type:bug
